"""Tests for peira.lockfile: lockfile drift detection.

Parsing handles both formats: uv.lock (PEP 751 TOML ``[[package]]``
sections, the current pin) and the legacy pip-compile layout (pins,
--hash continuations, via comments). Drift detection compares the
watchlist against installed versions with an injectable getter, so no
test depends on the machine's real environment.
"""

import io
import tempfile
import unittest
from contextlib import redirect_stderr
from pathlib import Path

from peira.lockfile import (
    check_drift,
    find_lockfile,
    read_lock_pins,
    warn_if_drifted,
)

LOCK_SAMPLE = """\
# This file is autogenerated by pip-compile
#
torch==2.14.1 \\
    --hash=sha256:aaa \\
    --hash=sha256:bbb
    # via peira
transformers==4.57.6 \\
    --hash=sha256:ccc
numpy==2.5.3
requests==2.32.0
    # via transformers
-e ./local-package
--extra-index-url https://example.com/simple
"""


class ReadLockPinsTests(unittest.TestCase):
    def _write(self, text):
        tmp = tempfile.NamedTemporaryFile(
            "w", suffix=".lock", delete=False, encoding="utf-8"
        )
        tmp.write(text)
        tmp.close()
        return Path(tmp.name)

    def test_parses_pins_skipping_hashes_and_comments(self):
        path = self._write(LOCK_SAMPLE)
        try:
            pins = read_lock_pins(path)
        finally:
            path.unlink()
        self.assertEqual(pins["torch"], "2.14.1")
        self.assertEqual(pins["transformers"], "4.57.6")
        self.assertEqual(pins["numpy"], "2.5.3")
        # Non-watchlist pins parse too; editable and index lines do not.
        self.assertEqual(pins["requests"], "2.32.0")
        self.assertNotIn("local-package", pins)
        self.assertNotIn("", pins)

    def test_name_normalization(self):
        path = self._write("My_Package==1.0\n")
        try:
            pins = read_lock_pins(path)
        finally:
            path.unlink()
        self.assertEqual(pins["my-package"], "1.0")

    def test_missing_file_raises_oserror(self):
        with self.assertRaises(OSError):
            read_lock_pins(Path("/nonexistent-dir/missing.lock"))


class CheckDriftTests(unittest.TestCase):
    PINS = {"torch": "2.14.1", "transformers": "4.57.6", "numpy": "2.5.3"}

    def test_no_drift_when_versions_match(self):
        installed = lambda pkg: self.PINS[pkg]  # noqa: E731
        self.assertEqual(
            check_drift(pins=dict(self.PINS), installed=installed), []
        )

    def test_reports_each_drifted_package(self):
        installed = {"torch": "2.14.1", "transformers": "4.50.0",
                     "numpy": "2.0.0"}.get
        drifts = check_drift(pins=dict(self.PINS), installed=installed)
        by_pkg = {d.package: d for d in drifts}
        self.assertEqual(set(by_pkg), {"transformers", "numpy"})
        self.assertEqual(by_pkg["transformers"].pinned, "4.57.6")
        self.assertEqual(by_pkg["transformers"].installed, "4.50.0")

    def test_uninstalled_package_is_not_drift(self):
        # A missing package fails fast at adapter init; the drift
        # check must not double-report it.
        installed = lambda pkg: None  # noqa: E731
        self.assertEqual(
            check_drift(pins=dict(self.PINS), installed=installed), []
        )

    def test_unwatchlisted_packages_ignored(self):
        pins = dict(self.PINS, requests="1.0")
        installed = lambda pkg: "9.9.9"  # noqa: E731
        drifts = check_drift(pins=pins, installed=installed)
        self.assertNotIn("requests", [d.package for d in drifts])

    def test_broken_getter_never_raises(self):
        def boom(pkg):
            raise RuntimeError("metadata broken")
        self.assertEqual(
            check_drift(pins=dict(self.PINS), installed=boom), []
        )


class WarnIfDriftedTests(unittest.TestCase):
    class _HFish:
        uses_local_ml_stack = True

    class _APIish:
        uses_local_ml_stack = False

    def test_no_marker_no_warning(self):
        err = io.StringIO()
        with redirect_stderr(err):
            drifts = warn_if_drifted(self._APIish(), stream=err)
        self.assertEqual(drifts, [])
        self.assertEqual(err.getvalue(), "")

    def test_find_lockfile_resolves_repo_pin(self):
        # The drift check is only meaningful against the real pinned
        # lockfile; this pins the resolution, not the versions. uv.lock
        # is the current pin and takes precedence over the legacy
        # requirements/all.lock (deleted from current checkouts).
        found = find_lockfile()
        self.assertIsNotNone(found)
        self.assertEqual(found.name, "uv.lock")
        pins = read_lock_pins(found)
        self.assertIn("torch", pins)

    def test_no_marker_attribute_no_warning(self):
        err = io.StringIO()
        with redirect_stderr(err):
            drifts = warn_if_drifted(object(), stream=err)
        self.assertEqual(drifts, [])
        self.assertEqual(err.getvalue(), "")

    def test_warning_prints_on_drift(self):
        import peira.lockfile as lockfile_mod

        real = lockfile_mod.check_drift
        lockfile_mod.check_drift = lambda: [
            lockfile_mod.Drift("torch", "2.14.1", "2.0.0")
        ]
        try:
            err = io.StringIO()
            with redirect_stderr(err):
                drifts = warn_if_drifted(self._HFish(), stream=err)
        finally:
            lockfile_mod.check_drift = real
        self.assertEqual(len(drifts), 1)
        self.assertIn("torch", err.getvalue())
        self.assertIn("2.14.1", err.getvalue())
        self.assertIn("2.0.0", err.getvalue())

    def test_broken_check_is_silent(self):
        import peira.lockfile as lockfile_mod

        real = lockfile_mod.check_drift

        def boom():
            raise RuntimeError("broken")

        lockfile_mod.check_drift = boom
        try:
            err = io.StringIO()
            with redirect_stderr(err):
                drifts = warn_if_drifted(self._HFish(), stream=err)
        finally:
            lockfile_mod.check_drift = real
        self.assertEqual(drifts, [])
        self.assertEqual(err.getvalue(), "")

    def test_warning_names_found_lockfile(self):
        import peira.lockfile as lockfile_mod

        real = lockfile_mod.check_drift
        lockfile_mod.check_drift = lambda: [
            lockfile_mod.Drift("torch", "2.14.1", "2.0.0")
        ]
        try:
            err = io.StringIO()
            with redirect_stderr(err):
                warn_if_drifted(self._HFish(), stream=err)
        finally:
            lockfile_mod.check_drift = real
        # The repo root pins uv.lock; the warning must name the
        # lockfile it actually compared against, not the legacy one.
        self.assertIn("uv.lock", err.getvalue())
        self.assertNotIn("requirements/all.lock", err.getvalue())


UV_SAMPLE = """\
# This file is autogenerated by uv
version = 1
requires-python = ">=3.10"

[[package]]
name = "torch"
version = "2.14.1"
source = { registry = "https://pypi.org/simple" }

[[package]]
name = "my_package"
version = "1.0"

[package.metadata]
requires-dist = [{ name = "requests" }]

[[package]]
name = "numpy"
version = "2.5.3"
"""

UV_DUPLICATE_PACKAGE = """\
[[package]]
name = "torch"
version = "2.14.1"
marker = "sys_platform == 'linux'"

[[package]]
name = "torch"
version = "2.14.0"
marker = "sys_platform == 'darwin'"
"""


class UvLockPinsTests(unittest.TestCase):
    def _write_named(self, dirname, filename, text):
        path = Path(dirname) / filename
        path.write_text(text, encoding="utf-8")
        return path

    def test_parses_package_name_version_pairs(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = self._write_named(tmp, "uv.lock", UV_SAMPLE)
            pins = read_lock_pins(path)
        self.assertEqual(
            pins,
            {"torch": "2.14.1", "my-package": "1.0", "numpy": "2.5.3"},
        )

    def test_format_version_line_is_not_a_pin(self):
        # The top-level `version = 1` sits outside any [[package]]
        # section and must never be mistaken for a pin.
        with tempfile.TemporaryDirectory() as tmp:
            path = self._write_named(tmp, "uv.lock", UV_SAMPLE)
            pins = read_lock_pins(path)
        self.assertNotIn("1", pins.values())

    def test_subsections_do_not_leak_pins(self):
        # [package.metadata] ends the package section; its
        # requires-dist entries are not pins.
        with tempfile.TemporaryDirectory() as tmp:
            path = self._write_named(tmp, "uv.lock", UV_SAMPLE)
            pins = read_lock_pins(path)
        self.assertNotIn("requests", pins)

    def test_first_duplicate_package_wins(self):
        # uv.lock can repeat a package name for different markers;
        # the first pin stands.
        with tempfile.TemporaryDirectory() as tmp:
            path = self._write_named(tmp, "uv.lock", UV_DUPLICATE_PACKAGE)
            pins = read_lock_pins(path)
        self.assertEqual(pins["torch"], "2.14.1")

    def test_dispatch_is_by_filename(self):
        # A uv.lock file parses as TOML even with pip-compile-like
        # content; a legacy-named file parses as pip-compile.
        with tempfile.TemporaryDirectory() as tmp:
            uv_path = self._write_named(tmp, "uv.lock", LOCK_SAMPLE)
            legacy_path = self._write_named(tmp, "all.lock", LOCK_SAMPLE)
            self.assertEqual(read_lock_pins(uv_path), {})
            self.assertEqual(read_lock_pins(legacy_path)["torch"], "2.14.1")


class FindLockfilePreferenceTests(unittest.TestCase):
    def _fake_root(self, names):
        import peira.lockfile as lockfile_mod

        tmp = tempfile.TemporaryDirectory()
        root = Path(tmp.name)
        for name in names:
            p = root / name
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text("torch==2.14.1\n", encoding="utf-8")
        real = lockfile_mod._repo_root
        lockfile_mod._repo_root = lambda: root  # noqa: E731
        self.addCleanup(setattr, lockfile_mod, "_repo_root", real)
        self.addCleanup(tmp.cleanup)

    def test_prefers_uv_lock_over_legacy(self):
        import peira.lockfile as lockfile_mod

        self._fake_root(["uv.lock", "requirements/all.lock"])
        found = lockfile_mod.find_lockfile()
        self.assertEqual(found.name, "uv.lock")

    def test_falls_back_to_legacy_lockfile(self):
        import peira.lockfile as lockfile_mod

        self._fake_root(["requirements/all.lock"])
        found = lockfile_mod.find_lockfile()
        self.assertTrue(found.as_posix().endswith("requirements/all.lock"))
        self.assertEqual(read_lock_pins(found)["torch"], "2.14.1")

    def test_none_when_no_lockfile_present(self):
        import peira.lockfile as lockfile_mod

        self._fake_root([])
        self.assertIsNone(lockfile_mod.find_lockfile())


if __name__ == "__main__":
    unittest.main()
