//! Cross-language parity tests: the Rust serialization must be
//! byte-identical to the Python reference implementation.
//!
//! Fixtures are generated by `tests/fixtures/generate.py` (run from the
//! repo root) from the live Python reference. If these tests fail after a
//! Python-side serialization change, regenerate the fixtures — do not
//! "fix" the Rust side to match stale expectations without checking the
//! Python reference first.

use peira_core::artifact::{lock_payload, RunArtifact};
use peira_core::canonical::{to_canonical, to_pretty};
use serde_json::Value;

fn fixture(name: &str) -> String {
    let path = format!("{}/tests/fixtures/{name}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read_to_string(&path)
        .unwrap_or_else(|_| panic!("missing fixture {path}; run generate.py"))
}

#[test]
fn float_parity_with_python() {
    let mut n = 0;
    for line in fixture("float_parity.txt").lines() {
        let (hex, want) = line.split_once(' ').expect("fixture format");
        let bits = u64::from_str_radix(hex, 16).expect("hex bits");
        let f = f64::from_bits(bits);
        let got = to_canonical(&Value::from(f));
        assert_eq!(got, want, "float bits {hex}");
        n += 1;
    }
    assert!(n > 2000, "sweep too small: {n}");
}

#[test]
fn string_parity_with_python() {
    // Each fixture line is a Python-produced JSON string literal; the
    // canonical encoding of its decoded value must reproduce it exactly.
    let mut n = 0;
    for line in fixture("string_parity.txt").lines() {
        let s: String = serde_json::from_str(line).expect("fixture is a string literal");
        let got = to_canonical(&Value::String(s));
        assert_eq!(got, line);
        n += 1;
    }
    assert!(n > 500, "sweep too small: {n}");
}

#[test]
fn analysis_lock_parity_with_python() {
    let mut n = 0;
    for line in fixture("lock_parity.jsonl").lines() {
        let row: Value = serde_json::from_str(line).unwrap();
        let art = &row["artifact"];
        let got = lock_payload(
            art["peira_version"].as_str().unwrap(),
            art["dataset_version"].as_str().unwrap(),
            art["manifest_sha256"].as_str().unwrap(),
            art["adapter_name"].as_str().unwrap(),
            art["adapter_version"].as_str().unwrap(),
            art["suite"].as_str().unwrap(),
            &art["config"],
            &art["results"],
            &art["metrics"],
            art["pricing_source"].as_str().unwrap(),
            art["pricing_date"].as_str().unwrap(),
            art["seed"].as_i64().unwrap(),
            art["max_concurrency"].as_i64().unwrap(),
        );
        assert_eq!(got, row["lock"].as_str().unwrap(), "lock mismatch");

        // A Python-sealed artifact verifies in Rust, and Rust's pretty
        // JSON is byte-identical to Python's to_json().
        let artifact: RunArtifact = serde_json::from_value(art.clone()).expect("artifact parses");
        assert!(artifact.verify(), "python-sealed artifact must verify");
        assert_eq!(to_pretty(art), row["pretty"].as_str().unwrap());
        // Round-trip: parse the pretty JSON back and re-verify.
        let back = RunArtifact::from_json(row["pretty"].as_str().unwrap()).expect("pretty parses");
        assert!(back.verify());
        n += 1;
    }
    assert!(n >= 2);
}

#[test]
fn case_extras_parity_with_python() {
    // Each fixture line is the Python reference's canonical
    // `Case.from_dict(c).to_dict()` for a case dict carrying unknown
    // top-level keys. Rust must reproduce it byte-for-byte: unknown keys
    // survive in `extras` and serialize back at the top level, exactly
    // where Python's `to_dict` puts them.
    use peira_core::schema::Case;
    let mut n = 0;
    for line in fixture("case_extras.jsonl").lines() {
        let v: Value = serde_json::from_str(line).expect("fixture parses");
        let case = Case::from_value(&v).expect("case parses");
        assert!(
            !case.extras.is_empty() || !line.contains("review_priority"),
            "extras lost on {line}"
        );
        let got = to_canonical(&serde_json::to_value(&case).expect("serializes"));
        assert_eq!(got, line, "extras round-trip mismatch");
        n += 1;
    }
    assert_eq!(n, 4, "fixture row count changed");
}
