#!/usr/bin/env python3
"""Generate docs/CLI.md from the live argparse parser (stdlib only).

Reads peira.cli:build_parser() — never executes a command, makes no
network calls — and renders every command, subcommand, flag, default,
and help string. The checked-in docs/CLI.md is generated, never
hand-edited (same pattern as scripts/gen_readme_table.py).

Usage:
    python3 scripts/gen_cli_reference.py            # write docs/CLI.md
    python3 scripts/gen_cli_reference.py --check docs/CLI.md
        # exit 0 if the file matches a fresh render, else exit 1
        # (this is what CI runs; the reference can never silently go stale)
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "python"))

from peira.cli import build_parser  # noqa: E402  (read-only: builds the parser, runs nothing)


def _escape(cell: str) -> str:
    return cell.replace("|", "\\|").replace("\n", " ")


def _default(action: argparse.Action) -> str:
    if isinstance(action, argparse._HelpAction):
        return ""
    if isinstance(action, argparse._VersionAction):
        return ""
    d = action.default
    if d is argparse.SUPPRESS:
        return "—"
    if d is None:
        return "—"
    return f"`{d!r}`"


def _flag_cell(action: argparse.Action) -> str:
    if action.option_strings:
        return " ".join(f"`{o}`" for o in action.option_strings)
    metavar = action.metavar or action.dest.upper()
    return f"`{metavar}`"


def _help_cell(action: argparse.Action) -> str:
    help_text = (action.help or "").strip()
    if action.choices and not isinstance(action, argparse._SubParsersAction):
        try:
            choices = ", ".join(f"`{c}`" for c in sorted(action.choices))
        except TypeError:
            choices = ", ".join(f"`{c}`" for c in action.choices)
        help_text = f"{help_text} (choices: {choices})".strip()
    return help_text


def _is_subparsers(action: argparse.Action) -> bool:
    return isinstance(action, argparse._SubParsersAction)


def _render_flags(parser: argparse.ArgumentParser) -> list[str]:
    lines = ["| Flag | Required | Default | Help |", "|---|---|---|---|"]
    for action in parser._actions:
        if isinstance(action, (argparse._HelpAction, argparse._SubParsersAction)):
            continue
        required = "yes" if getattr(action, "required", False) else ""
        lines.append(
            f"| {_escape(_flag_cell(action))} | {required} "
            f"| {_escape(_default(action))} | {_escape(_help_cell(action))} |"
        )
    return lines


def _walk_with_help(parser: argparse.ArgumentParser, path: list[str],
                    level: int, out: list[str], help_text: str) -> None:
    title = " ".join(["peira", *path])
    out.append(f"{'#' * level} {title}")
    out.append("")
    if help_text:
        out.append(help_text.strip())
        out.append("")
    flags = _render_flags(parser)
    if len(flags) > 2:
        out.extend(flags)
        out.append("")
    for action in parser._actions:
        if not _is_subparsers(action):
            continue
        for name in action.choices:
            _walk_with_help(action.choices[name], [*path, name], level + 1,
                            out, help_text=_subcommand_help(parser, name))


def _subcommand_help(parent: argparse.ArgumentParser, name: str) -> str:
    for action in parent._actions:
        if _is_subparsers(action):
            # add_parser(help=...) is stashed on the subparser by argparse
            # only via the pseudo-action; recover from _choices_actions.
            for choice_action in action._choices_actions:
                if choice_action.dest == name:
                    return choice_action.help or ""
    return ""


def render() -> str:
    parser = build_parser()
    out = [
        "# CLI reference",
        "",
        "> DO NOT EDIT — generated by `scripts/gen_cli_reference.py` from the",
        "> live argparse parser (`peira.cli:build_parser`). Regenerate with",
        "> `python3 scripts/gen_cli_reference.py`. CI fails on drift.",
        "",
        "Every flag, default, and help string below comes from the parser",
        "itself. For what the numbers mean, see",
        "[Methodology](Methodology.md); for exact error text, see",
        "[Troubleshooting](Troubleshooting.md).",
        "",
    ]
    _walk_top(parser, out)
    return "\n".join(out).rstrip() + "\n"


def _walk_top(parser: argparse.ArgumentParser, out: list[str]) -> None:
    description = (parser.description or "").strip()
    if description:
        out.append(description)
        out.append("")
    flags = _render_flags(parser)
    if len(flags) > 2:
        out.append("## Global flags")
        out.append("")
        out.extend(flags)
        out.append("")
    for action in parser._actions:
        if not _is_subparsers(action):
            continue
        for name in action.choices:
            _walk_with_help(action.choices[name], [name], 2, out,
                            _subcommand_help(parser, name))


def main() -> int:
    check_path = None
    args = sys.argv[1:]
    if args[:1] == ["--check"]:
        if len(args) != 2:
            print("usage: gen_cli_reference.py --check <docs/CLI.md>",
                  file=sys.stderr)
            return 2
        check_path = Path(args[1])
    elif args:
        print(f"usage: gen_cli_reference.py [--check <docs/CLI.md>]",
              file=sys.stderr)
        return 2
    rendered = render()
    if check_path is not None:
        current = check_path.read_text(encoding="utf-8")
        if current == rendered:
            print("docs/CLI.md matches the live parser.")
            return 0
        diff = "".join(difflib.unified_diff(
            current.splitlines(keepends=True),
            rendered.splitlines(keepends=True),
            fromfile="docs/CLI.md (checked in)",
            tofile="docs/CLI.md (regenerated)"))
        print("docs/CLI.md is stale — regenerate with "
              "python3 scripts/gen_cli_reference.py:\n", file=sys.stderr)
        print(diff, file=sys.stderr)
        return 1
    target = REPO_ROOT / "docs" / "CLI.md"
    target.write_text(rendered, encoding="utf-8")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
