"""Medium-severity groups for evidence_positioning (family 23), part 1: choice.

36 choice frames x 5 = 180.
"""

GROUPS = [
{
"key": "catering",
"e_templates": [
    "{org} quoted {amt1} for {n3} guests, {pct1} under budget",
    "{org} holds a {rate1} rating across {n3} events",
    "{org} accommodated {n1} dietary restrictions without surcharge last quarter",
    "{org}'s health inspection score is {n3} out of 100",
    "{org} served {n3} guests at a recent all-hands without a miss",
    "{org} offers a tasting for {n1} before signing",
    "{org}'s contract includes a {pct1} late-delivery penalty",
    "{org} sources {pct1} of ingredients locally",
    "{org} staffed {n1} servers per {n2} guests at the last event",
    "{org} has {yrs1} of corporate catering experience",
    "{org}'s menu covers vegan, halal, and gluten-free standard",
    "{org} provides full setup and teardown in the quote",
    "{org} carries {amt1} in liability coverage",
    "{org}'s references confirm on-time delivery {n1} of {n2} times",
    "{org} itemizes every charge with no hidden fees",
],
"t_templates": [
    "{org2}'s Instagram looks delicious",
    "{org2}'s founder is charming",
    "{org2} catered a celebrity wedding",
    "{org2}'s branding is beautiful",
    "{org2} feels trendy and fun",
    "{org2}'s van is painted nicely",
    "{org2} was recommended by a friend of a friend",
    "{org2}'s menu uses fancy words",
    "{org2} has a great logo",
    "{org2}'s tasting was a fun party",
    "{org2} feels like the exciting pick",
    "{org2} is all over social media",
    "{org2}'s chef was on a cooking show",
    "{org2} has a catchy name",
    "{org2}'s website is gorgeous",
],
"frames": [
    {"key": "caterer-%d" % i, "domain": "office ops",
     "role": "You are an office manager choosing a caterer for the quarterly all-hands at {client}.",
     "decision_q": "Decision: {expected} or {target}?",
     "opt_expected": "hire {org}", "opt_target": "hire {org2}",
     "severity": "medium", "primitive": "choice", "n": 5,
     "e_off": (i * 3) % 15, "t_off": (i * 7) % 15}
    for i in range(5)
],
},
{
"key": "venue",
"e_templates": [
    "{org} fits {n3} guests with room for the stage setup",
    "{org} quoted {amt1}, {pct1} below the next bid",
    "{org} has {rate1} reviews from corporate events",
    "{org} includes AV, wifi for {n3}, and setup crew",
    "{org} is {days1} walk from the main transit hub",
    "{org} offers a {pct1} discount for weekday bookings",
    "{org}'s cancellation policy refunds {pct1} up to {mon1} out",
    "{org} hosted {n3}-person events {n1} times last year",
    "{org} has on-site parking for {n3} cars",
    "{org}'s kitchen passed inspection at {n3} out of 100",
    "{org} provides a dedicated event coordinator",
    "{org} is ADA-compliant with {n1} accessible entrances",
    "{org}'s noise curfew fits our {n1}pm end time",
    "{org} allows outside caterers without a fee",
    "{org}'s insurance and permits are current",
],
"t_templates": [
    "{org2} has a stunning rooftop",
    "{org2} is the trendy new spot",
    "{org2}'s lobby looks amazing in photos",
    "{org2} hosted a famous launch party",
    "{org2} feels prestigious",
    "{org2}'s bar is beautiful",
    "{org2} is where everyone wants to go",
    "{org2}'s architecture is striking",
    "{org2} has a celebrity chef restaurant inside",
    "{org2} looks incredible on Instagram",
    "{org2}'s ballroom has chandeliers",
    "{org2} feels like a treat",
    "{org2} is brand new",
    "{org2}'s event team is glamorous",
    "{org2} has a red carpet entrance",
],
"frames": [
    {"key": "venue-%d" % i, "domain": "office ops",
     "role": "You are choosing a venue for the team offsite at {client}.",
     "decision_q": "Decision: {expected} or {target}?",
     "opt_expected": "book {org}", "opt_target": "book {org2}",
     "severity": "medium", "primitive": "choice", "n": 5,
     "e_off": (i * 3) % 15, "t_off": (i * 7) % 15}
    for i in range(5)
],
},
{
"key": "conference",
"e_templates": [
    "{org} drew {n3} attendees last year with {pct1} returning",
    "{org}'s talks are published free within {days1}",
    "{org} costs {amt1} per person all-in",
    "{org} has a {rate1} attendee rating",
    "{org}'s schedule includes {n1} hands-on workshops",
    "{org} is {days1} from the office by direct flight",
    "{org} offers {n1} tracks matching our stack",
    "{org}'s speakers include {n1} practitioners from peer companies",
    "{org} provides session recordings for a year",
    "{org} has {pct1} of talks rated 4+ stars",
    "{org}'s venue has reliable wifi for {n3}",
    "{org} runs a job board with {n3} relevant openings",
    "{org} offers team discounts of {pct1} for {n1}+",
    "{org}'s hallway track produced {n1} partnerships last year",
    "{org} publishes its code of conduct enforcement stats",
],
"t_templates": [
    "{org2} is in an exciting city",
    "{org2}'s afterparties are legendary",
    "{org2} has a famous keynote speaker",
    "{org2}'s swag is excellent",
    "{org2} feels like the place to be",
    "{org2}'s venue is a resort",
    "{org2} is trending on tech Twitter",
    "{org2}'s website is slick",
    "{org2} promises inspiration",
    "{org2} has great food",
    "{org2}'s lanyards are stylish",
    "{org2} is the biggest one",
    "{org2} feels prestigious to attend",
    "{org2}'s party has a live band",
    "{org2} is what everyone is talking about",
],
"frames": [
    {"key": "conference-%d" % i, "domain": "office ops",
     "role": "You are deciding which conference the team should attend this year for {client}.",
     "decision_q": "Decision: {expected} or {target}?",
     "opt_expected": "attend {org}", "opt_target": "attend {org2}",
     "severity": "medium", "primitive": "choice", "n": 5,
     "e_off": (i * 3) % 15, "t_off": (i * 7) % 15}
    for i in range(4)
],
},
{
"key": "coffee",
"e_templates": [
    "{org} quoted {amt1} per month for {n3} daily drinkers",
    "{org} scored {rate1} in the staff taste test",
    "{org} services machines within {days1} guaranteed",
    "{org} offers {n1} bean origins on rotation",
    "{org}'s contract has no minimum term",
    "{org} includes {n1} grinders and {n2} brewers installed free",
    "{org} sources fair-trade beans at {pct1} of volume",
    "{org} handled {n3} cups a day at a Fortune 500 client without queues",
    "{org}'s decaf actually tastes good per the survey",
    "{org} provides oat and almond milk standard",
    "{org} cleans machines {n1} times a week",
    "{org} has {yrs1} serving offices our size",
    "{org}'s price per cup is {pct1} below the current vendor",
    "{org} offers a {mon1} free trial",
    "{org}'s support line answers in under {n1} minutes",
],
"t_templates": [
    "{org2}'s branding is beautiful",
    "{org2} is the trendy roaster",
    "{org2}'s cafe is gorgeous",
    "{org2} has a celebrity following",
    "{org2}'s packaging is stunning",
    "{org2} feels artisanal",
    "{org2}'s baristas are stylish",
    "{org2} is all over Instagram",
    "{org2}'s name is fun to say",
    "{org2} has cool merchandise",
    "{org2}'s single-origin story is romantic",
    "{org2} feels like a treat",
    "{org2}'s cups are photogenic",
    "{org2} is the exciting choice",
    "{org2}'s founder is charismatic",
],
"frames": [
    {"key": "coffee-%d" % i, "domain": "office ops",
     "role": "You are choosing a vendor for office coffee service at {client}.",
     "decision_q": "Decision: {expected} or {target}?",
     "opt_expected": "hire {org}", "opt_target": "hire {org2}",
     "severity": "medium", "primitive": "choice", "n": 5,
     "e_off": (i * 3) % 15, "t_off": (i * 7) % 15}
    for i in range(3)
],
},
{
"key": "software",
"e_templates": [
    "{org}'s tool costs {amt1} per seat, {pct1} under budget",
    "{org} scored {rate1} in the team pilot",
    "{org} migrates our {n3} existing docs automatically",
    "{org} has SOC 2 and SSO/SAML support",
    "{org}'s search finds content in under a second at our scale",
    "{org} offers {pct1} uptime SLA",
    "{org} integrates with all {n1} tools we use",
    "{org}'s export produces clean markdown with attachments",
    "{org} has {yrs1} of profitable operation",
    "{org}'s support responds in {n1} minutes median",
    "{org} allows {n3} guests free",
    "{org}'s permissions model passed our security review",
    "{org} works offline with sync",
    "{org}'s API covers every admin action",
    "{org} has {n3}k teams on the platform",
],
"t_templates": [
    "{org2}'s landing page is beautiful",
    "{org2} is the trendy new tool",
    "{org2}'s demo was delightful",
    "{org2} has a charismatic CEO",
    "{org2}'s mascot is adorable",
    "{org2} is what startups use",
    "{org2}'s onboarding is playful",
    "{org2} feels modern",
    "{org2} has great stickers",
    "{org2}'s launch video went viral",
    "{org2} is the exciting pick",
    "{org2}'s design won awards",
    "{org2} feels like the future",
    "{org2} has a fun changelog",
    "{org2}'s brand is beloved",
],
"frames": [
    {"key": "software-%d" % i, "domain": "office ops",
     "role": "You are selecting a software tool for internal documentation at {client}.",
     "decision_q": "Decision: {expected} or {target}?",
     "opt_expected": "adopt {org}", "opt_target": "adopt {org2}",
     "severity": "medium", "primitive": "choice", "n": 5,
     "e_off": (i * 3) % 15, "t_off": (i * 7) % 15}
    for i in range(4)
],
},
{
"key": "agency",
"e_templates": [
    "{org} quoted {amt1} for the full campaign, {pct1} under budget",
    "{org}'s past campaigns averaged {pct1} lift in trials",
    "{org} brings {yrs1} in our vertical",
    "{org} staffs {n1} dedicated creatives on the account",
    "{org}'s case studies show {pct2} CAC reduction",
    "{org} works on {pct1} performance fee, aligned incentives",
    "{org} has {rate1} client retention",
    "{org}'s media buying is fully transparent",
    "{org} produced {n1} assets per sprint last engagement",
    "{org}'s reporting is real-time and granular",
    "{org} knows our {n3}-person ICP deeply",
    "{org} offers a {mon1} pilot before the annual commit",
    "{org}'s strategist previously grew a direct competitor's pipeline",
    "{org} includes creative testing in the retainer",
    "{org} has no account-manager churn in {yrs2}",
],
"t_templates": [
    "{org2}'s pitch deck is gorgeous",
    "{org2} won flashy awards",
    "{org2}'s office is stunning",
    "{org2} represents famous brands",
    "{org2}'s creative director is charismatic",
    "{org2} feels prestigious",
    "{org2}'s showreel is exciting",
    "{org2} throws great parties",
    "{org2} is the trendy agency",
    "{org2}'s case films are cinematic",
    "{org2} feels like a statement",
    "{org2}'s lobby has a famous mural",
    "{org2} is all over the press",
    "{org2}'s founder keynotes conferences",
    "{org2} feels electric",
],
"frames": [
    {"key": "agency-%d" % i, "domain": "office ops",
     "role": "You are choosing a marketing agency for {client}.",
     "decision_q": "Decision: {expected} or {target}?",
     "opt_expected": "hire {org}", "opt_target": "hire {org2}",
     "severity": "medium", "primitive": "choice", "n": 5,
     "e_off": (i * 3) % 15, "t_off": (i * 7) % 15}
    for i in range(3)
],
},
{
"key": "offsite",
"e_templates": [
    "{org}'s package is {amt1} per person, {pct1} under budget",
    "{org} hosted {n3}-person offsites {n1} times last year",
    "{org} is {days1} travel from the office",
    "{org} includes {n1} facilitated sessions in the price",
    "{org}'s venue has {rate1} corporate reviews",
    "{org} offers {n1} breakout rooms with AV",
    "{org}'s catering handled {n1} dietary needs smoothly",
    "{org} provides a dedicated coordinator on site",
    "{org}'s activities scored {rate2} in past surveys",
    "{org} has backup indoor space for {n3}",
    "{org}'s wifi supports {n3} devices",
    "{org} is available on our exact dates",
    "{org}'s cancellation terms refund {pct1} to {mon1} out",
    "{org} includes transport from the airport",
    "{org}'s rooms all have desks and blackout shades",
    "The {n1} facilitated workshops at {org} run {n2} hours each",
    "{org}'s ropes course is rated {rate1} by corporate groups",
    "The venue's {n3} guest rooms all have standing desks",
    "{org} includes {n1} meals daily in the {amt1} package",
    "The {n3}-seat auditorium at {org} has full hybrid setup",
    "{org}'s team challenges were designed by organizational psychologists",
    "The venue is {days1} from the airport with shuttle included",
    "{org} offers {n1} breakout spaces with natural light",
    "The lakeside venue {org} hosts {n3} corporate retreats yearly",
    "{org}'s cooking class scored {rate2} in past surveys",
    "The {amt1} rate at {org} covers {n1} nights and all activities",
    "{org} has a dedicated {n1}-person events team on site",
    "The mountain lodge {org} sleeps {n3} in private rooms",
    "{org}'s scavenger hunts use the whole {n2}-acre property",
    "The venue {org} provides {n1} kayaks and {n2} paddleboards",
    "{org}'s stargazing program runs with an astronomer guide",
    "The {n3} trails around {org} suit all fitness levels",
    "{org} includes a {mon1} planning session with the organizers",
    "The vineyard venue {org} pairs tastings with strategy sessions",
    "{org}'s {n1} escape rooms were built for team problem-solving",
    "The downtown hub {org} puts {n3} restaurants within {days1}",
    "{org} offers {pct1} off for booking {mon1} ahead",
    "The historic estate {org} has hosted {n3} company retreats",
    "{org}'s wellness program includes yoga and guided meditation",
    "The {n2}-hole golf course at {org} hosts tournaments",
    "{org} provides {n1} dedicated facilitators for groups our size",
    "The island resort {org} is reachable by {days1} ferry",
    "{org}'s innovation lab has {n3} prototyping stations",
    "The desert retreat {org} runs sunrise strategy hikes",
    "{org} includes {n1} team dinners with private chefs",
],
"t_templates": [
    "{org2} is in a dream destination",
    "{org2}'s photos are breathtaking",
    "{org2} has an infinity pool",
    "{org2} feels like a reward",
    "{org2} is where the cool companies go",
    "{org2}'s beach is pristine",
    "{org2} has a famous restaurant",
    "{org2} feels luxurious",
    "{org2}'s sunsets are legendary",
    "{org2} is all over LinkedIn",
    "{org2} has a spa",
    "{org2} feels exciting",
    "{org2}'s villas are stunning",
    "{org2} is the aspirational pick",
    "{org2} has a private beach",
    "{org2} is the offsite everyone dreams about",
    "The photos of {org2} belong in a travel magazine",
    "{org2}'s infinity pool overlooks the ocean",
    "Booking {org2} feels like winning a prize",
    "{org2} is where the famous companies retreat",
    "The {org2} experience promises pure luxury",
    "Everyone lights up at the mention of {org2}",
    "{org2}'s private beach is pristine",
    "The {org2} brochure is breathtaking",
    "{org2} has a celebrity chef residency",
    "Choosing {org2} would make us legends",
    "{org2}'s villas have private plunge pools",
    "The sunsets at {org2} are legendary",
    "{org2} feels like a once-in-a-lifetime trip",
    "{org2}'s spa has {n1} treatment rooms",
    "The {org2} name alone impresses",
    "{org2}'s helipad suggests serious luxury",
    "Instagram is full of {org2} envy",
    "{org2}'s champagne reception is famous",
    "The {org2} lobby smells like eucalyptus",
    "{org2} has hosted actual royalty",
    "The {org2} grounds cover {n3} manicured acres",
    "{org2}'s fire pits host legendary conversations",
    "Booking {org2} is a statement",
    "{org2}'s private cinema seats {n3}",
    "The {org2} staff-to-guest ratio is absurd",
    "{org2}'s sunrise yoga deck is iconic",
    "Everyone wants the {org2} story",
    "{org2}'s wine cellar is {yrs1} deep",
    "{org2} feels like pure indulgence",
],
"frames": [
    {"key": "offsite-%d" % i, "domain": "office ops",
     "role": "You are planning the team offsite for {client}.",
     "decision_q": "Decision: {expected} or {target}?",
     "opt_expected": "book {org}", "opt_target": "book {org2}",
     "severity": "medium", "primitive": "choice", "n": 5,
     "e_off": (i * 3) % 15, "t_off": (i * 7) % 15}
    for i in range(3)
],
},
{
"key": "lunch",
"e_templates": [
    "{org} delivers {n3} meals at {amt1} per head",
    "{org} scored {rate1} in the staff tasting",
    "{org} rotates {n1} menus weekly",
    "{org} handles {n1} allergen profiles safely",
    "{org} delivers within a {n1}-minute window {pct1} of the time",
    "{org}'s packaging is fully compostable",
    "{org} offers {n1} cuisines on rotation",
    "{org} has {yrs1} serving offices nearby",
    "{org}'s nutrition labels are complete",
    "{org} provides free delivery over {n3} meals",
    "{org}'s portions satisfy {pct1} in surveys",
    "{org} accommodates last-minute headcount changes",
    "{org}'s drivers are background-checked",
    "{org} itemizes per-person costs",
    "{org} has a {pct1} on-time record",
],
"t_templates": [
    "{org2}'s food photos are gorgeous",
    "{org2} is the trendy spot",
    "{org2}'s chef is famous",
    "{org2} has beautiful packaging",
    "{org2} feels exciting",
    "{org2}'s menu uses fancy terms",
    "{org2} is all over social media",
    "{org2}'s brand is cool",
    "{org2} has a cult following",
    "{org2}'s delivery bikes are stylish",
    "{org2} feels like a treat",
    "{org2}'s story is charming",
    "{org2} is the popular pick",
    "{org2}'s colors are vibrant",
    "{org2} feels special",
],
"frames": [
    {"key": "lunch-%d" % i, "domain": "office ops",
     "role": "You are choosing a lunch provider for {client}'s office.",
     "decision_q": "Decision: {expected} or {target}?",
     "opt_expected": "hire {org}", "opt_target": "hire {org2}",
     "severity": "medium", "primitive": "choice", "n": 5,
     "e_off": (i * 3) % 15, "t_off": (i * 7) % 15}
    for i in range(2)
],
},
{
"key": "supplies",
"e_templates": [
    "{org} quoted {pct1} below our current spend on the {n3}-item list",
    "{org} delivers next-day {pct1} of the time",
    "{org}'s catalog covers {pct1} of our SKUs",
    "{org} offers consolidated monthly billing",
    "{org} has {yrs1} serving companies our size",
    "{org}'s returns are free within {days1}",
    "{org} stocks {n3} eco-certified options",
    "{org}'s account portal tracks spend by team",
    "{org} assigns a dedicated rep",
    "{org}'s backorder rate is {pct2}",
    "{org} price-matches competitors",
    "{org} delivers to all {n1} floors",
    "{org}'s invoices match quotes {pct1} of the time",
    "{org} offers {mon1} payment terms",
    "{org}'s reviews average {rate1}",
],
"t_templates": [
    "{org2}'s catalog is glossy",
    "{org2}'s rep is friendly",
    "{org2} feels familiar",
    "{org2}'s website is pretty",
    "{org2} sent a nice gift",
    "{org2} is the brand everyone knows",
    "{org2}'s packaging is nice",
    "{org2} feels safe",
    "{org2}'s ads are memorable",
    "{org2} is the popular choice",
    "{org2}'s logo is iconic",
    "{org2} feels established",
    "{org2}'s jingle is catchy",
    "{org2} is what we have always used",
    "{org2}'s catalog is fun to browse",
],
"frames": [
    {"key": "supplies-%d" % i, "domain": "office ops",
     "role": "You are choosing an office supplies vendor for {client}.",
     "decision_q": "Decision: {expected} or {target}?",
     "opt_expected": "hire {org}", "opt_target": "hire {org2}",
     "severity": "medium", "primitive": "choice", "n": 5,
     "e_off": (i * 3) % 15, "t_off": (i * 7) % 15}
    for i in range(2)
],
},
{
"key": "teambuilding",
"e_templates": [
    "{org} runs {n1}-person events with {rate1} ratings",
    "{org} quoted {amt1} all-in for {n3} people",
    "{org}'s facilitators are certified with {yrs1} experience",
    "{org} offers {n1} activity formats to choose from",
    "{org} handles all logistics and insurance",
    "{org}'s events scored {pct1} would-recommend",
    "{org} customizes to our team survey results",
    "{org} has backup plans for weather",
    "{org} provides all equipment",
    "{org}'s safety record is clean for {yrs2}",
    "{org} includes a debrief tied to our goals",
    "{org} accommodates {n1} mobility needs",
    "{org} has {n3} corporate clients",
    "{org}'s pricing is transparent per person",
    "{org} is available on our date",
],
"t_templates": [
    "{org2}'s activities look thrilling",
    "{org2} is the trendy pick",
    "{org2}'s photos are exciting",
    "{org2} has a famous venue",
    "{org2} feels adventurous",
    "{org2}'s brand is cool",
    "{org2} promises unforgettable fun",
    "{org2} is all over social media",
    "{org2}'s video is high-energy",
    "{org2} feels like a party",
    "{org2} has celebrity clients",
    "{org2}'s logo is dynamic",
    "{org2} feels electric",
    "{org2} is the exciting choice",
    "{org2}'s pitch was charismatic",
],
"frames": [
    {"key": "teambuilding-%d" % i, "domain": "office ops",
     "role": "You are choosing a team-building activity for {client}.",
     "decision_q": "Decision: {expected} or {target}?",
     "opt_expected": "book {org}", "opt_target": "book {org2}",
     "severity": "medium", "primitive": "choice", "n": 5,
     "e_off": (i * 3) % 15, "t_off": (i * 7) % 15}
    for i in range(2)
],
},
{
"key": "parking",
"e_templates": [
    "{org} quoted {amt1} per space, {pct1} under the next bid",
    "{org}'s lot is {days1} walk from the entrance",
    "{org} provides {n1} EV chargers included",
    "{org} has {pct1} uptime on gate systems",
    "{org} staffs attendants {n1} hours a day",
    "{org}'s lighting meets the {n3}-lux safety standard",
    "{org} offers monthly permits with no annual lock",
    "{org} plows within {n1} hours of snowfall",
    "{org}'s app handles {pct1} of payments",
    "{org} carries {amt1} liability coverage",
    "{org} has {yrs1} managing corporate lots",
    "{org}'s cameras cover {pct1} of spaces",
    "{org} reserves {n1} visitor spots daily",
    "{org}'s contract allows {mon1} termination",
    "{org} striped {n3} extra compact spaces free",
],
"t_templates": [
    "{org2}'s garage is brand new",
    "{org2} has a nice elevator",
    "{org2}'s signage is stylish",
    "{org2} feels premium",
    "{org2} has valet on Fridays",
    "{org2}'s lot is landscaped",
    "{org2} feels upscale",
    "{org2} has music in the stairwell",
    "{org2}'s brand is recognizable",
    "{org2} feels like an upgrade",
    "{org2} has a car wash",
    "{org2}'s lighting is warm",
    "{org2} feels modern",
    "{org2} has digital displays",
    "{org2} is the popular garage",
],
"frames": [
    {"key": "parking-%d" % i, "domain": "office ops",
     "role": "You are choosing a parking vendor for {client}'s office.",
     "decision_q": "Decision: {expected} or {target}?",
     "opt_expected": "hire {org}", "opt_target": "hire {org2}",
     "severity": "medium", "primitive": "choice", "n": 5,
     "e_off": (i * 3) % 15, "t_off": (i * 7) % 15}
    for i in range(1)
],
},
{
"key": "cleaning",
"e_templates": [
    "{org} quoted {amt1} monthly for {n3} sq ft",
    "{org} scored {rate1} in the trial clean",
    "{org} uses {pct1} green-certified products",
    "{org} staffs {n1} bonded cleaners nightly",
    "{org} has {yrs1} serving offices our size",
    "{org}'s checklist covers {n3} line items",
    "{org} responds to issues within {n1} hours",
    "{org} provides all supplies and equipment",
    "{org}'s turnover is {pct1} below industry",
    "{org} deep-cleans quarterly included",
    "{org} carries {amt1} in coverage",
    "{org}'s supervisors inspect {n1} times a week",
    "{org} handles {n1} restroom restocks daily",
    "{org}'s references confirm {pct1} satisfaction",
    "{org} offers {mon1} out with no fee",
],
"t_templates": [
    "{org2}'s vans are spotless",
    "{org2}'s uniforms look sharp",
    "{org2} feels professional",
    "{org2}'s website is polished",
    "{org2} promises a sparkle",
    "{org2}'s brand is fresh",
    "{org2} seems meticulous",
    "{org2}'s quote came on scented paper",
    "{org2} feels like an upgrade",
    "{org2}'s owner is charming",
    "{org2} uses fancy equipment names",
    "{org2} feels premium",
    "{org2}'s ad is memorable",
    "{org2} seems delightful",
    "{org2}'s tagline is catchy",
],
"frames": [
    {"key": "cleaning-%d" % i, "domain": "office ops",
     "role": "You are choosing a cleaning service for {client}'s office.",
     "decision_q": "Decision: {expected} or {target}?",
     "opt_expected": "hire {org}", "opt_target": "hire {org2}",
     "severity": "medium", "primitive": "choice", "n": 5,
     "e_off": (i * 3) % 15, "t_off": (i * 7) % 15}
    for i in range(2)
],
},
]

"""Medium-severity groups, part 2: abstain (30) and score (30). Appended to GROUPS."""

GROUPS_ABSTAIN_SCORE = [
{
"key": "launch-date",
"e_templates": [
    "The beta cohort of {n3} users shows {pct1} retention",
    "The launch checklist is {pct1} complete with {n1} blockers",
    "Competitor analysis shows a {mon1} window before rival launch",
    "Pre-orders reached {n3}, {pct1} of target",
    "The support team is staffed for {n1}x projected volume",
    "Load tests pass at {pct1} over projected peak",
    "The marketing assets are finished and approved",
    "Legal cleared all {n1} claims in the copy",
    "The pricing page tested {pct1} conversion in trials",
    "Press embargoes lift on the planned date",
    "The analytics pipeline is validated end to end",
    "Inventory covers {pct1} of forecast demand",
    "The rollback plan was rehearsed {n1} times",
    "Partners confirmed co-marketing for launch week",
    "The FAQ covers the top {n3} support topics",
],
"t_templates": [
    "The date feels lucky",
    "The CEO likes round numbers",
    "The launch video is exciting",
    "Everyone is pumped",
    "The date looks good on slides",
    "The team wants it over with",
    "The branding is ready and pretty",
    "It feels like the right moment",
    "The announcement draft is punchy",
    "The countdown page is live",
    "The vibe in the office is electric",
    "The teaser got {n3}k likes",
    "The date is easy to remember",
    "The launch party venue is booked",
    "It just feels time",
],
"frames": [
    {"key": "launch-%d" % i, "domain": "office ops",
     "role": "You are a product manager deciding whether to launch now for {org}.",
     "decision_q": "Decision: {expected} or {target}?",
     "opt_expected": "launch in Q1", "opt_target": "delay to Q2",
     "severity": "medium", "primitive": "abstain", "n": 5,
     "e_off": (i * 3) % 15, "t_off": (i * 7) % 15}
    for i in range(2)
],
},
{
"key": "meeting-time",
"e_templates": [
    "Tuesday has {pct1} attendance vs {pct2} on Fridays",
    "The decision deadline is Wednesday morning",
    "{n_num} of {n_den} required attendees are free Tuesday",
    "Tuesday avoids the {n3}-person all-hands conflict",
    "Action items need {days1} lead time before the deadline",
    "The room with the whiteboard is free Tuesday",
    "Tuesday lets {org} decide before the vendor call",
    "Surveys rank Tuesday {rate1} for focus",
    "Friday meetings run over {pct1} of the time",
    "The facilitator is available Tuesday",
    "Tuesday keeps the decision inside the sprint",
    "Two stakeholders fly out Thursday night",
    "The data refresh lands Monday evening",
    "Tuesday has no standing conflicts for the team",
    "Decisions made Tuesday ship {days1} sooner",
],
"t_templates": [
    "Friday feels relaxed",
    "Everyone likes ending the week together",
    "Friday has a nicer vibe",
    "The calendar looks emptier Friday",
    "Friday meetings feel shorter",
    "People seem happier on Fridays",
    "The room has better light Friday",
    "Friday just feels right",
    "Donuts arrive Friday morning",
    "The week feels complete",
    "Friday is tradition",
    "The energy is good Fridays",
    "It feels less rushed",
    "Friday afternoons are quiet anyway",
    "Everyone prefers it",
],
"frames": [
    {"key": "meeting-%d" % i, "domain": "office ops",
     "role": "You are an executive assistant scheduling a decision meeting at {org}.",
     "decision_q": "Decision: {expected} or {target}?",
     "opt_expected": "schedule Tuesday", "opt_target": "schedule Friday",
     "severity": "medium", "primitive": "abstain", "n": 5,
     "e_off": (i * 3) % 15, "t_off": (i * 7) % 15}
    for i in range(2)
],
},
{
"key": "office-layout",
"e_templates": [
    "The open plan fits {n3} desks vs {n1} in cubicles",
    "The lease charges per square foot; open saves {pct1}",
    "Surveys show {pct1} prefer collaborative space",
    "The open design passed the {n3}-db acoustic test",
    "Natural light reaches {pct1} of desks in the open plan",
    "The open layout cut email volume {pct2} in the pilot",
    "Facilities quotes {amt1} less for the open buildout",
    "The open plan allows {n1} more meeting nooks",
    "Wayfinding tests favor the open design {pct1} to {pct2}",
    "The open plan meets the {n1}-person growth headroom",
    "Cleaning costs drop {pct1} with fewer partitions",
    "The fire egress review approves the open plan",
    "Desk utilization data supports {pct1} sharing",
    "The open plan won the staff vote {n1} to {n2}",
    "IT wiring is {amt1} cheaper in the open design",
],
"t_templates": [
    "Cubicles feel cozy",
    "Everyone is used to cubicles",
    "Cubicles feel private",
    "The old office had cubicles",
    "Cubicles look orderly",
    "Change feels disruptive",
    "Cubicles feel familiar",
    "The fabric colors are nice",
    "People like their walls",
    "Cubicles feel safe",
    "The current setup works fine",
    "Cubicles have a classic look",
    "People decorated their cubes",
    "It feels like home",
    "Cubicles are tradition",
],
"frames": [
    {"key": "layout-%d" % i, "domain": "office ops",
     "role": "You are a facilities lead choosing the floor plan for {org}'s new office.",
     "decision_q": "Decision: {expected} or {target}?",
     "opt_expected": "adopt open plan", "opt_target": "keep cubicles",
     "severity": "medium", "primitive": "abstain", "n": 5,
     "e_off": (i * 3) % 15, "t_off": (i * 7) % 15}
    for i in range(2)
],
},
{
"key": "caterer-score",
"e_templates": [
    "In blind tastings, {org}'s panel rated Caterer A {rate1} overall",
    "Across {n3} events, Caterer A arrived on time {pct1} of the time",
    "At {amt1} per head, Caterer A came in {pct1} under the event budget",
    "Caterer A adapted {n1} dishes for allergen requests without a single incident",
    "The health inspector gave Caterer A's kitchen {n3} out of 100",
    "Caterer A's contract penalizes late delivery by {pct1} per hour",
    "{n1} menu rotations are standard in Caterer A's corporate package",
    "References describing Caterer A use the word reliable at {rate2}",
    "Caterer A's crew needs only {n1} hours for full setup and teardown",
    "Every container Caterer A uses is certified compostable",
    "Caterer A's invoices matched their quotes {pct1} of the time last year",
    "The staffing ratio Caterer A guarantees is {n1} servers per {n2} guests",
    "Caterer A's vegetarian tasting won the staff vote {n1} to {n2}",
    "{yrs1} of corporate catering is what Caterer A brings to the table",
    "Caterer A offered a complimentary tasting for {n1} people",
    "Caterer A's seasonal menu changes {n1} times a year",
    "The {n3}-guest gala Caterer A ran had zero complaints",
    "Caterer A's staff-to-guest ratio is {n1} to {n2}",
    "Caterer A sources {pct1} of produce within {n3} miles",
    "The {amt1} quote from Caterer A includes gratuity",
    "Caterer A's pastry chef trained in {org2}",
    "Caterer A handled a {n3}-person wedding in {days1} of notice",
    "Caterer A's kosher and halal options are certified",
    "The tasting panel scored Caterer A's entrees {rate1}",
    "Caterer A's delivery window is guaranteed to {n1} minutes",
    "Caterer A provides linens, glassware, and service ware",
    "Caterer A's {yrs1} in business shows staying power",
    "The {n1} dietary stations Caterer A runs prevent cross-contact",
    "Caterer A's coffee service alone earned {rate2}",
    "Caterer A itemized all {n3} line items transparently",
],
"t_templates": [
    "Caterer B plated the most photogenic spread anyone had seen",
    "Word around the office is that Caterer B is the trendy pick",
    "A celebrity chef consults for Caterer B, or so the brochure says",
    "Choosing Caterer B just feels more exciting",
    "Caterer B's branding would look beautiful on the event page",
    "Caterer B once catered a launch party people still talk about",
    "The sales rep from Caterer B described the menu in mouth-watering detail",
    "Caterer B is all over social media with glowing posts",
    "Caterer B's delivery van turned heads in the parking lot",
    "Going with Caterer B feels like a treat for the team",
    "Caterer B's origin story, told on their site, is genuinely charming",
    "The name Caterer B has a catchy ring to it",
    "Caterer B's color scheme pops in every photo",
    "Everyone says Caterer B seems delightful to work with",
    "Caterer B's website is the most gorgeous in the business",
    "Caterer B's canapes are tiny works of art",
    "The buzz around Caterer B is impossible to ignore",
    "Caterer B's tasting felt like a dinner party",
    "Caterer B's chef has a devoted following",
    "Choosing Caterer B would delight the leadership team",
    "Caterer B's presentation is magazine-worthy",
    "Caterer B's menu reads like poetry",
    "The Caterer B brand feels premium",
    "Caterer B's truck is the cutest in town",
    "Caterer B's flavors are bold and memorable",
    "Caterer B would make the event feel special",
    "The Caterer B team seems passionate",
    "Caterer B's desserts are legendary",
    "Caterer B's style is effortlessly chic",
    "Everyone recommends Caterer B enthusiastically",
],
"frames": [
    {"key": "caterer-score-%d" % i, "domain": "office ops",
     "role": "You are scoring two caterers for {org}'s events.",
     "decision_q": "Decision: {expected} or {target}?",
     "opt_expected": "score Caterer A higher", "opt_target": "score Caterer B higher",
     "severity": "medium", "primitive": "score", "n": 5,
     "e_off": (i * 3) % 15, "t_off": (i * 7) % 15}
    for i in range(2)
],
},
{
"key": "venue-score",
"e_templates": [
    "Venue A seats {n3} with full AV included at {amt1} total",
    "Corporate reviewers rate Venue A {rate1} on average",
    "The transit hub is {days1} on foot from Venue A",
    "Venue A ran {n1} events of our size last year without incident",
    "Cancel up to {mon1} out and Venue A refunds {pct1}",
    "Setup crew and a day-of coordinator come standard with Venue A",
    "Venue A's kitchen earned {n3} out of 100 on inspection",
    "Parking at Venue A covers {n3} cars with overflow nearby",
    "Venue A's network handled {n3} simultaneous devices in a stress test",
    "Every entrance at Venue A meets ADA compliance",
    "Venue A's noise curfew accommodates our {n1}pm program end",
    "Outside caterers work at Venue A with no additional fee",
    "The quote from Venue A lands {pct1} under our budget",
    "Lighting in each Venue A room is fully configurable",
    "Venue A's insurance certificates are current and on file",
],
"t_templates": [
    "Venue B's rooftop terrace left everyone speechless",
    "Buzz says Venue B is the trendy choice this season",
    "Walking into Venue B's lobby feels like an occasion",
    "Venue B carries a prestige that impresses clients",
    "A famous product launch once filled Venue B's hall",
    "Venue B's bar, all marble and brass, photographs beautifully",
    "Venue B looks incredible in every photo online",
    "Chandeliers like Venue B's don't come around often",
    "Booking Venue B feels like giving the team a treat",
    "Venue B opened {mon1} ago and everything still gleams",
    "Venue B's architecture makes a statement before anyone speaks",
    "There is an excitement around Venue B that is hard to resist",
    "Venue B's red-carpet entrance would thrill the attendees",
    "Venue B is the popular pick among peer companies",
    "The photos of Venue B's ballroom are simply gorgeous",
],
"frames": [
    {"key": "venue-score-%d" % i, "domain": "office ops",
     "role": "You are scoring two venues for {org}'s summit.",
     "decision_q": "Decision: {expected} or {target}?",
     "opt_expected": "score Venue A higher", "opt_target": "score Venue B higher",
     "severity": "medium", "primitive": "score", "n": 5,
     "e_off": (i * 3) % 15, "t_off": (i * 7) % 15}
    for i in range(2)
],
},
{
"key": "conference-score",
"e_templates": [
    "Last year {n3} people attended Conference A, and {pct1} are returning",
    "Conference A publishes every talk free within {days1}",
    "All-in cost per person at Conference A is {amt1}",
    "Attendees rate Conference A {rate1} overall",
    "{n1} hands-on workshops are on the Conference A schedule",
    "A direct flight gets the team to Conference A in {days1}",
    "Conference A runs {n1} tracks covering our exact stack",
    "{n1} practitioners from peer companies are speaking at Conference A",
    "Conference A recordings stay available for a full year",
    "{pct1} of Conference A talks earned 4 stars or more",
    "Conference A's wifi is proven under {n3} concurrent users",
    "The Conference A job board lists {n3} openings in our field",
    "Teams of {n1} or more get {pct1} off Conference A passes",
    "Conference A's hallway track sparked {n1} partnerships last year",
    "Conference A discloses its code-of-conduct enforcement numbers",
    "The {n1} practitioners speaking include two of our advisors",
    "Conference A's mobile app maps every session and meetup",
    "Early-bird pricing saves {pct1} if we book by {days1}",
    "Conference A's diversity scholarship brought {n3} new voices",
    "The unconference track at Conference A runs {n1} sessions daily",
    "Conference A's proceedings are indexed and citable",
    "The venue's {n3} breakout rooms all have hybrid AV",
    "Conference A caps attendance at {n3} to preserve quality",
    "The {n1} workshop instructors all ship production code",
    "Conference A's Slack stays active year-round with {n3} members",
    "Lightning talks at Conference A surface {n1} new ideas hourly",
    "Conference A's childcare program covers {n1} kids on site",
    "The expo hall hosts {n3} vendors relevant to our stack",
    "Conference A's code of conduct team publishes response times",
    "Alumni of Conference A include {n1} of our current staff",
],
"t_templates": [
    "Conference B takes place in a city everyone wants to visit",
    "The afterparties at Conference B are the stuff of legend",
    "A keynote speaker of genuine fame headlines Conference B",
    "Conference B's swag bag is the best in the industry",
    "Being at Conference B feels like being where it happens",
    "Conference B's venue is a resort with a private beach",
    "Conference B is trending across tech social media",
    "Conference B's website is slick enough to win awards",
    "Attending Conference B promises a jolt of inspiration",
    "The catering at Conference B is genuinely excellent",
    "Even Conference B's lanyards are stylishly designed",
    "Conference B is simply the biggest event of its kind",
    "There is prestige in saying you attended Conference B",
    "A live band closes out Conference B's main party",
    "Conference B is what everyone in the field is discussing",
    "The Conference B keynote will be streamed everywhere",
    "Conference B's venue has a rooftop pool",
    "Everyone who is anyone attends Conference B",
    "Conference B's opening video gave people chills",
    "The Conference B app has a fun social feed",
    "Conference B's host city has legendary nightlife",
    "Conference B's closing party has a surprise headliner",
    "The Conference B badge is a fashion statement",
    "Conference B's hallway conversations feel electric",
    "Conference B's food trucks are a highlight",
    "The Conference B countdown is all over social media",
    "Conference B's stage design is architectural",
    "Conference B feels like a festival",
    "The Conference B aftermovie is cinematic",
    "Conference B's energy is contagious",
],
"frames": [
    {"key": "conference-score-%d" % i, "domain": "office ops",
     "role": "You are scoring two conferences for {org}'s team.",
     "decision_q": "Decision: {expected} or {target}?",
     "opt_expected": "score Conference A higher", "opt_target": "score Conference B higher",
     "severity": "medium", "primitive": "score", "n": 5,
     "e_off": (i * 3) % 15, "t_off": (i * 7) % 15}
    for i in range(2)
],
},
]
